/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-22-2010
 * 
 * XDoclet definition:
 * @struts.form name="eIForm"
 */
public class ElementaryProcessForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** eiDesp property */
	private String epDesp;

	/** epType property */
	private String epType;

	/** eiName property */
	private String epName;

	/** ufpCount property */
	private String ufpCount;

	/** functionId property */
	private String functionId;

	/** ufpMethod property */
	private String ufpMethod;

	/** id property */
	private String id;
	
	/** measureStatus property */
	private String measureStatus;
	

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the eiDesp.
	 * @return String
	 */
	public String getEpDesp() {
		return epDesp;
	}

	/** 
	 * Set the eiDesp.
	 * @param eiDesp The eiDesp to set
	 */
	public void setEpDesp(String epDesp) {
		this.epDesp = epDesp;
	}

	/** 
	 * Returns the epType.
	 * @return String
	 */
	public String getEpType() {
		return epType;
	}

	/** 
	 * Set the epType.
	 * @param epType The epType to set
	 */
	public void setEpType(String epType) {
		this.epType = epType;
	}

	/** 
	 * Returns the eiName.
	 * @return String
	 */
	public String getEpName() {
		return epName;
	}

	/** 
	 * Set the eiName.
	 * @param eiName The eiName to set
	 */
	public void setEpName(String epName) {
		this.epName = epName;
	}

	/** 
	 * Returns the ufpCount.
	 * @return String
	 */
	public String getUfpCount() {
		return ufpCount;
	}

	/** 
	 * Set the ufpCount.
	 * @param ufpCount The ufpCount to set
	 */
	public void setUfpCount(String ufpCount) {
		this.ufpCount = ufpCount;
	}

	/** 
	 * Returns the functionId.
	 * @return String
	 */
	public String getFunctionId() {
		return functionId;
	}

	/** 
	 * Set the functionId.
	 * @param functionId The functionId to set
	 */
	public void setFunctionId(String functionId) {
		this.functionId = functionId;
	}

	/** 
	 * Returns the ufpMethod.
	 * @return String
	 */
	public String getUfpMethod() {
		return ufpMethod;
	}

	/** 
	 * Set the ufpMethod.
	 * @param ufpMethod The ufpMethod to set
	 */
	public void setUfpMethod(String ufpMethod) {
		this.ufpMethod = ufpMethod;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
	/** 
	 * Returns the measureStatus.
	 * @return String
	 */
	public String getMeasureStatus() {
		return measureStatus;
	}

	/** 
	 * Set the measureStatus.
	 * @param measureStatus The measureStatus to set
	 */
	public void setMeasureStatus(String measureStatus) {
		this.measureStatus = measureStatus;
	}
}