/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-01-2010
 * 
 * XDoclet definition:
 * @struts.form name="epDetForm"
 */
public class EpDetForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** epDetName property */
	private String epDetName;

	/** epDetDesp property */
	private String epDetDesp;

	/** epType property */
	private String type;

	/** id property */
	private String id;

	/** epId property */
	private String epId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the epDetName.
	 * @return String
	 */
	public String getEpDetName() {
		return epDetName;
	}

	/** 
	 * Set the epDetName.
	 * @param epDetName The epDetName to set
	 */
	public void setEpDetName(String epDetName) {
		this.epDetName = epDetName;
	}

	/** 
	 * Returns the epDetDesp.
	 * @return String
	 */
	public String getEpDetDesp() {
		return epDetDesp;
	}

	/** 
	 * Set the epDetDesp.
	 * @param epDetDesp The epDetDesp to set
	 */
	public void setEpDetDesp(String epDetDesp) {
		this.epDetDesp = epDetDesp;
	}



	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the epId.
	 * @return String
	 */
	public String getEpId() {
		return epId;
	}

	/** 
	 * Set the epId.
	 * @param epId The epId to set
	 */
	public void setEpId(String epId) {
		this.epId = epId;
	}
}