/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-13-2010
 * 
 * XDoclet definition:
 * @struts.form name="fpForm"
 */
public class FpForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** vaf property */
	private String vaf;

	/** fp property */
	private String fpc;

	/** productId property */
	private String productId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the vaf.
	 * @return String
	 */
	public String getVaf() {
		return vaf;
	}

	/** 
	 * Set the vaf.
	 * @param vaf The vaf to set
	 */
	public void setVaf(String vaf) {
		this.vaf = vaf;
	}


	public String getFpc() {
		return fpc;
	}

	public void setFpc(String fpc) {
		this.fpc = fpc;
	}

	/** 
	 * Returns the productId.
	 * @return String
	 */
	public String getProductId() {
		return productId;
	}

	/** 
	 * Set the productId.
	 * @param productId The productId to set
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}
}