/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-11-2010
 * 
 * XDoclet definition:
 * @struts.form name="functionForm"
 */
public class FunctionForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** measureStatus property */
	private String measureStatus;

	/** productId property */
	private String productId;

	/** functionType property */
	private String functionType;

	/** father property */
	private String fatherId;

	/** functionName property */
	private String functionName;

	/** id property */
	private String id;

	/** upfCount property */
	private String upfCount;

	/** functionDesp property */
	private String functionDesp;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the measureStatus.
	 * @return String
	 */
	public String getMeasureStatus() {
		return measureStatus;
	}

	/** 
	 * Set the measureStatus.
	 * @param measureStatus The measureStatus to set
	 */
	public void setMeasureStatus(String measureStatus) {
		this.measureStatus = measureStatus;
	}

	/** 
	 * Returns the productId.
	 * @return String
	 */
	public String getProductId() {
		return productId;
	}

	/** 
	 * Set the productId.
	 * @param productId The productId to set
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}

	/** 
	 * Returns the functionType.
	 * @return String
	 */
	public String getFunctionType() {
		return functionType;
	}

	/** 
	 * Set the functionType.
	 * @param functionType The functionType to set
	 */
	public void setFunctionType(String functionType) {
		this.functionType = functionType;
	}

	/** 
	 * Returns the father.
	 * @return String
	 */
	public String getFatherId() {
		return fatherId;
	}

	/** 
	 * Set the father.
	 * @param father The father to set
	 */
	public void setFatherId(String fatherId) {
		this.fatherId = fatherId;
	}

	/** 
	 * Returns the functionName.
	 * @return String
	 */
	public String getFunctionName() {
		return functionName;
	}

	/** 
	 * Set the functionName.
	 * @param functionName The functionName to set
	 */
	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the upfCount.
	 * @return String
	 */
	public String getUpfCount() {
		return upfCount;
	}

	/** 
	 * Set the upfCount.
	 * @param upfCount The upfCount to set
	 */
	public void setUpfCount(String upfCount) {
		this.upfCount = upfCount;
	}

	/** 
	 * Returns the functionDesp.
	 * @return String
	 */
	public String getFunctionDesp() {
		return functionDesp;
	}

	/** 
	 * Set the functionDesp.
	 * @param functionDesp The functionDesp to set
	 */
	public void setFunctionDesp(String functionDesp) {
		this.functionDesp = functionDesp;
	}
}