/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-08-2010
 * 
 * XDoclet definition:
 * @struts.form name="productForm"
 */
public class ProductForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** measureStatus property */
	private String measureStatus;

	/** estimateTime property */
	private String estimateTime;

	/** lifecyclePhase property */
	private String lifecyclePhase;

	/** productName property */
	private String productName;

	/** projectEndTime property */
	private String projectEndTime;

	/** id property */
	private String id;

	/** endTime property */
	private String endTime;

	/** productType property */
	private String productType;

	/** projectSarteTime property */
	private String projectStartTime;

	/** productDesp property */
	private String productDesp;

	/** measureMethod property */
	private String measureMethod;

	/** developType property */
	private String developType;

	/** estimator property */
	private String estimator;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the measureStatus.
	 * @return String
	 */
	public String getMeasureStatus() {
		return measureStatus;
	}

	/** 
	 * Set the measureStatus.
	 * @param measureStatus The measureStatus to set
	 */
	public void setMeasureStatus(String measureStatus) {
		this.measureStatus = measureStatus;
	}

	/** 
	 * Returns the estimateTime.
	 * @return String
	 */
	public String getEstimateTime() {
		return estimateTime;
	}

	/** 
	 * Set the estimateTime.
	 * @param estimateTime The estimateTime to set
	 */
	public void setEstimateTime(String estimateTime) {
		this.estimateTime = estimateTime;
	}

	/** 
	 * Returns the lifecyclePhase.
	 * @return String
	 */
	public String getLifecyclePhase() {
		return lifecyclePhase;
	}

	/** 
	 * Set the lifecyclePhase.
	 * @param lifecyclePhase The lifecyclePhase to set
	 */
	public void setLifecyclePhase(String lifecyclePhase) {
		this.lifecyclePhase = lifecyclePhase;
	}

	/** 
	 * Returns the productName.
	 * @return String
	 */
	public String getProductName() {
		return productName;
	}

	/** 
	 * Set the productName.
	 * @param productName The productName to set
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/** 
	 * Returns the projectEndTime.
	 * @return String
	 */
	public String getProjectEndTime() {
		return projectEndTime;
	}

	/** 
	 * Set the projectEndTime.
	 * @param projectEndTime The projectEndTime to set
	 */
	public void setProjectEndTime(String projectEndTime) {
		this.projectEndTime = projectEndTime;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the endTime.
	 * @return String
	 */
	public String getEndTime() {
		return endTime;
	}

	/** 
	 * Set the endTime.
	 * @param endTime The endTime to set
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	/** 
	 * Returns the productType.
	 * @return String
	 */
	public String getProductType() {
		return productType;
	}

	/** 
	 * Set the productType.
	 * @param productType The productType to set
	 */
	public void setProductType(String productType) {
		this.productType = productType;
	}

	/** 
	 * Returns the projectSarteTime.
	 * @return String
	 */
	public String getProjectStartTime() {
		return projectStartTime;
	}

	/** 
	 * Set the projectSarteTime.
	 * @param projectSarteTime The projectSarteTime to set
	 */
	public void setProjectStartTime(String projectStartTime) {
		this.projectStartTime = projectStartTime;
	}

	/** 
	 * Returns the productDesp.
	 * @return String
	 */
	public String getProductDesp() {
		return productDesp;
	}

	/** 
	 * Set the productDesp.
	 * @param productDesp The productDesp to set
	 */
	public void setProductDesp(String productDesp) {
		this.productDesp = productDesp;
	}

	/** 
	 * Returns the measureMethod.
	 * @return String
	 */
	public String getMeasureMethod() {
		return measureMethod;
	}

	/** 
	 * Set the measureMethod.
	 * @param measureMethod The measureMethod to set
	 */
	public void setMeasureMethod(String measureMethod) {
		this.measureMethod = measureMethod;
	}

	/** 
	 * Returns the developType.
	 * @return String
	 */
	public String getDevelopType() {
		return developType;
	}

	/** 
	 * Set the developType.
	 * @param developType The developType to set
	 */
	public void setDevelopType(String developType) {
		this.developType = developType;
	}

	/** 
	 * Returns the estimator.
	 * @return String
	 */
	public String getEstimator() {
		return estimator;
	}

	/** 
	 * Set the estimator.
	 * @param estimator The estimator to set
	 */
	public void setEstimator(String estimator) {
		this.estimator = estimator;
	}
}