/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-02-2010
 * 
 * XDoclet definition:
 * @struts.form name="ufpCountForm"
 */
public class UfpCountForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** complexValue property */
	private String complexValue;

	/** value_det property */
	private String value_det;

	/** range_ret property */
	private String range_ret;

	/** ufpCount property */
	private String ufpCount;

	/** value_ret property */
	private String value_ret;

	/** range_det property */
	private String range_det;
	
	/** ufpMethod property */
	private String ufpMethod;

	/** type property */
	private String type;
	
	/** dfId property */
	private String dfId;
	
	/** defaultMethod property */
	private String defaultMethod;
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the complexValue.
	 * @return String
	 */
	public String getComplexValue() {
		return complexValue;
	}

	/** 
	 * Set the complexValue.
	 * @param complexValue The complexValue to set
	 */
	public void setComplexValue(String complexValue) {
		this.complexValue = complexValue;
	}

	/** 
	 * Returns the value_det.
	 * @return String
	 */
	public String getValue_det() {
		return value_det;
	}

	/** 
	 * Set the value_det.
	 * @param value_det The value_det to set
	 */
	public void setValue_det(String value_det) {
		this.value_det = value_det;
	}

	/** 
	 * Returns the range_ret.
	 * @return String
	 */
	public String getRange_ret() {
		return range_ret;
	}

	/** 
	 * Set the range_ret.
	 * @param range_ret The range_ret to set
	 */
	public void setRange_ret(String range_ret) {
		this.range_ret = range_ret;
	}

	/** 
	 * Returns the ufpCount.
	 * @return String
	 */
	public String getUfpCount() {
		return ufpCount;
	}

	/** 
	 * Set the ufpCount.
	 * @param ufpCount The ufpCount to set
	 */
	public void setUfpCount(String ufpCount) {
		this.ufpCount = ufpCount;
	}

	/** 
	 * Returns the value_ret.
	 * @return String
	 */
	public String getValue_ret() {
		return value_ret;
	}

	/** 
	 * Set the value_ret.
	 * @param value_ret The value_ret to set
	 */
	public void setValue_ret(String value_ret) {
		this.value_ret = value_ret;
	}

	/** 
	 * Returns the range_det.
	 * @return String
	 */
	public String getRange_det() {
		return range_det;
	}

	/** 
	 * Set the range_det.
	 * @param range_det The range_det to set
	 */
	public void setRange_det(String range_det) {
		this.range_det = range_det;
	}

	public String getUfpMethod() {
		return ufpMethod;
	}

	public void setUfpMethod(String ufpMethod) {
		this.ufpMethod = ufpMethod;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDfId() {
		return dfId;
	}

	public void setDfId(String dfId) {
		this.dfId = dfId;
	}

	public String getDefaultMethod() {
		return defaultMethod;
	}

	public void setDefaultMethod(String defaultMethod) {
		this.defaultMethod = defaultMethod;
	}
	
}