/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-28-2010
 * 
 * XDoclet definition:
 * @struts.form name="dataFunctionForm"
 */
public class DataFunctionForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** type property */
	private String type;

	/** ufpCount property */
	private String ufpCount;

	/** ufpMethod property */
	private String ufpMethod;

	/** name property */
	private String name;

	/** desp property */
	private String desp;

	/** id property */
	private String id;
	
	private String productId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the type.
	 * @return String
	 */
	public String getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(String type) {
		this.type = type;
	}

	/** 
	 * Returns the ufpCount.
	 * @return String
	 */
	public String getUfpCount() {
		return ufpCount;
	}

	/** 
	 * Set the ufpCount.
	 * @param ufpCount The ufpCount to set
	 */
	public void setUfpCount(String ufpCount) {
		this.ufpCount = ufpCount;
	}

	/** 
	 * Returns the ufpMethod.
	 * @return String
	 */
	public String getUfpMethod() {
		return ufpMethod;
	}

	/** 
	 * Set the ufpMethod.
	 * @param ufpMethod The ufpMethod to set
	 */
	public void setUfpMethod(String ufpMethod) {
		this.ufpMethod = ufpMethod;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the desp.
	 * @return String
	 */
	public String getDesp() {
		return desp;
	}

	/** 
	 * Set the desp.
	 * @param desp The desp to set
	 */
	public void setDesp(String desp) {
		this.desp = desp;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}
	
}