/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-01-2010
 * 
 * XDoclet definition:
 * @struts.form name="detForm"
 */
public class DetForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** type property */
	private String type;

	/** detDesp property */
	private String detDesp;

	/** retId property */
	private String retId;

	/** detName property */
	private String detName;

	/** id property */
	private String id;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the typeId.
	 * @return String
	 */
	public String getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The typeId to set
	 */
	public void setType(String type) {
		this.type = type;
	}

	/** 
	 * Returns the detDesp.
	 * @return String
	 */
	public String getDetDesp() {
		return detDesp;
	}

	/** 
	 * Set the detDesp.
	 * @param detDesp The detDesp to set
	 */
	public void setDetDesp(String detDesp) {
		this.detDesp = detDesp;
	}

	/** 
	 * Returns the retId.
	 * @return String
	 */
	public String getRetId() {
		return retId;
	}

	/** 
	 * Set the retId.
	 * @param retId The retId to set
	 */
	public void setRetId(String retId) {
		this.retId = retId;
	}

	/** 
	 * Returns the detName.
	 * @return String
	 */
	public String getDetName() {
		return detName;
	}

	/** 
	 * Set the detName.
	 * @param detName The detName to set
	 */
	public void setDetName(String detName) {
		this.detName = detName;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
}