/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-27-2010
 * 
 * XDoclet definition:
 * @struts.form name="ufpCountOfEpForm"
 */
public class UfpCountOfEpForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** complex property */
	private String complex;

	/** eiId property */
	private String epId;
	
	private String type;

	/** defaultUfp property */
	private String defaultUfp;

	/** ftrValue property */
	private String ftrValue;

	/** ufpValue property */
	private String ufpValue;

	/** ftrRange property */
	private String ftrRange;

	/** detRange property */
	private String detRange;

	/** methodType property */
	private String ufpMethod;

	/** detValue property */
	private String detValue;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the complex.
	 * @return String
	 */
	public String getComplex() {
		return complex;
	}

	/** 
	 * Set the complex.
	 * @param complex The complex to set
	 */
	public void setComplex(String complex) {
		this.complex = complex;
	}

	public String getEpId() {
		return epId;
	}

	public void setEpId(String epId) {
		this.epId = epId;
	}


	/** 
	 * Returns the defaultUfp.
	 * @return String
	 */
	public String getDefaultUfp() {
		return defaultUfp;
	}

	/** 
	 * Set the defaultUfp.
	 * @param defaultUfp The defaultUfp to set
	 */
	public void setDefaultUfp(String defaultUfp) {
		this.defaultUfp = defaultUfp;
	}

	/** 
	 * Returns the ftrValue.
	 * @return String
	 */
	public String getFtrValue() {
		return ftrValue;
	}

	/** 
	 * Set the ftrValue.
	 * @param ftrValue The ftrValue to set
	 */
	public void setFtrValue(String ftrValue) {
		this.ftrValue = ftrValue;
	}

	/** 
	 * Returns the ufpValue.
	 * @return String
	 */
	public String getUfpValue() {
		return ufpValue;
	}

	/** 
	 * Set the ufpValue.
	 * @param ufpValue The ufpValue to set
	 */
	public void setUfpValue(String ufpValue) {
		this.ufpValue = ufpValue;
	}

	/** 
	 * Returns the ftrRange.
	 * @return String
	 */
	public String getFtrRange() {
		return ftrRange;
	}

	/** 
	 * Set the ftrRange.
	 * @param ftrRange The ftrRange to set
	 */
	public void setFtrRange(String ftrRange) {
		this.ftrRange = ftrRange;
	}

	/** 
	 * Returns the detRange.
	 * @return String
	 */
	public String getDetRange() {
		return detRange;
	}

	/** 
	 * Set the detRange.
	 * @param detRange The detRange to set
	 */
	public void setDetRange(String detRange) {
		this.detRange = detRange;
	}

	/** 
	 * Returns the methodType.
	 * @return String
	 */


	/** 
	 * Returns the detValue.
	 * @return String
	 */
	public String getDetValue() {
		return detValue;
	}

	/** 
	 * Set the detValue.
	 * @param detValue The detValue to set
	 */
	public void setDetValue(String detValue) {
		this.detValue = detValue;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUfpMethod() {
		return ufpMethod;
	}

	public void setUfpMethod(String ufpMethod) {
		this.ufpMethod = ufpMethod;
	}
}