/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.action;

import java.io.UnsupportedEncodingException;

import hibernate.IFPUG.IfpugFunction;
import hibernate.IFPUG.IfpugProduct;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.IFPUG.RequirementBusiness;
import struts.IFPUG.form.FunctionForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-16-2010
 * 
 * XDoclet definition:
 * @struts.action path="/addChildFunction" name="functionForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/IFPUG/requirement/functionList.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/IFPUG/failure.jsp" contextRelative="true"
 */
public class AddChildFunctionAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 * @throws UnsupportedEncodingException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException, UnsupportedEncodingException {
		FunctionForm functionForm = (FunctionForm) form;// TODO Auto-generated method stub
		
		//获取functionList.jsp页面传过来的functionId,此ID为欲添加子模块的父模块ID
		Integer functionId = new Integer(functionForm.getId());	
		IfpugFunction ifi = new IfpugFunction();
		RequirementBusiness rb = new RequirementBusiness();
		IfpugFunction function = (IfpugFunction)rb.getFunctionById(functionId);
		//IfpugProduct product = function.getIfpugProduct();
				
		//从form表单中获取Function信息,赋值给实体Bean 
		ifi.setMeasureStatus(Short.valueOf("0"));
		ifi.setIfpugProduct(null);
		ifi.setIfpugFunction(function);
		//ifi.setUfpCount(new Integer(functionForm.getUpfCount().toString()));
		ifi.setFunctionDesp(new String(functionForm.getFunctionDesp().getBytes("ISO-8859-1"),"gb2312"));
		ifi.setFunctionName(new String(functionForm.getFunctionName().getBytes("ISO-8859-1"),"gb2312"));
		ifi.setFunctionType(Short.valueOf(functionForm.getFunctionType()));
	
		//调用业务层函数增加待估算软件
		boolean result = rb.insertFunction(ifi);
		if(result==true){
		   return mapping.findForward("success");
		}else{
		   return mapping.findForward("failure");
		}
	}
}