/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.action;

import java.io.UnsupportedEncodingException;

import hibernate.IFPUG.IfpugEi;
import hibernate.IFPUG.IfpugEiDet;
import hibernate.IFPUG.IfpugEo;
import hibernate.IFPUG.IfpugEoDet;
import hibernate.IFPUG.IfpugEq;
import hibernate.IFPUG.IfpugEqDet;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.transaction.Transaction;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.IFPUG.TransactionFunctionBusiness;
import struts.IFPUG.form.EpDetForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-01-2010
 * 
 * XDoclet definition:
 * @struts.action path="/addEpDet" name="epDetForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/IFPUG/transaction/derivedMethod.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/IFPUG/failure.jsp" contextRelative="true"
 */
public class AddEpDetAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws UnsupportedEncodingException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws UnsupportedEncodingException {
		EpDetForm epDetForm = (EpDetForm) form;// TODO Auto-generated method stub
		

		Integer type = Integer.valueOf(epDetForm.getType());	//获取derivedMethod.jsp页面传过来的type	
		Integer epId = Integer.valueOf(epDetForm.getEpId());//获取传过来的id
		TransactionFunctionBusiness tfb = new TransactionFunctionBusiness();
		boolean result = false;
		switch(type)
		{
		case 0:
			IfpugEi ifpugEi = tfb.queryEiById(epId);
			IfpugEiDet eiDet = new IfpugEiDet();
			eiDet.setEiDetDesp(new String(epDetForm.getEpDetDesp().getBytes("ISO-8859-1"),"gb2312"));
			eiDet.setEiDetName(new String(epDetForm.getEpDetName().getBytes("ISO-8859-1"),"gb2312"));
			eiDet.setIfpugEi(ifpugEi);
			eiDet.setFileType(Short.valueOf("3"));
			try {
					result = tfb.insertDet(eiDet);
				} catch (HibernateException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}			
			break;
		case 1:
			IfpugEo ifpugEo = tfb.queryEoById(epId);
			IfpugEoDet eoDet = new IfpugEoDet();
			eoDet.setEoDetDesp(new String(epDetForm.getEpDetDesp().getBytes("ISO-8859-1"),"gb2312"));
			eoDet.setEoDetName(new String(epDetForm.getEpDetName().getBytes("ISO-8859-1"),"gb2312"));
			eoDet.setIfpugEo(ifpugEo);
			eoDet.setFileType(Short.valueOf("3"));
			try {
				result = tfb.insertDet(eoDet);
				} catch (HibernateException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			break;
		case 2:
			IfpugEq ifpugEq = tfb.queryEqById(epId);
			IfpugEqDet eqDet = new IfpugEqDet();
			eqDet.setEqDetDesp(new String(epDetForm.getEpDetDesp().getBytes("ISO-8859-1"),"gb2312"));
			eqDet.setEqDetName(new String(epDetForm.getEpDetName().getBytes("ISO-8859-1"),"gb2312"));
			eqDet.setIfpugEq(ifpugEq);
			eqDet.setFileType(Short.valueOf("3"));
			try {
				result = tfb.insertDet(eqDet);
				} catch (HibernateException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			break;
		}
		if(result==true){
			   return mapping.findForward("success");
		}else{
			   return mapping.findForward("failure");
		}
	}
}