/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.action;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.IFPUG.UserBusiness;

import entityOperation.IFPUG.UserDAO;
import struts.IFPUG.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-17-2011
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="userForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/IFPUG/ifpug.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/IFPUG/failure.jsp" contextRelative="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		String username=userForm.getUsername();
		String password=userForm.getPassword();
		UserBusiness ub = new UserBusiness();
		boolean isValidateUser = ub.isValidateUser(username, password);
		String key=null;
		if(isValidateUser==true){			
			key="success";
			request.getSession().setAttribute("userName", username);
			return mapping.findForward(key);
		}
		else{
			key="failure";
			response.setContentType("text/html;charset=UTF-8"); 
			response.getWriter().print(
		        "<script type='text/javascript' charset=‘gb2312’>alert('用户名或密码不正确，请重试！');location.href='/ifpug/index.jsp'</script>");
			return null;

		}
	}
}