/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.action;


import java.io.UnsupportedEncodingException;

import hibernate.IFPUG.IfpugEif;
import hibernate.IFPUG.IfpugIlf;
import hibernate.IFPUG.IfpugProduct;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.IFPUG.DataFunctionBusiness;
import business.IFPUG.RequirementBusiness;
import struts.IFPUG.form.DataFunctionForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-28-2010
 * 
 * XDoclet definition:
 * @struts.action path="/addDataFunction" name="dataFunctionForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/IFPUG/dataFunction/ilfList.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/IFPUG/failure.jsp" contextRelative="true"
 */
public class AddDataFunctionAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 * @throws UnsupportedEncodingException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException, UnsupportedEncodingException {
		DataFunctionForm dataFunctionForm = (DataFunctionForm) form;// TODO Auto-generated method stub
		boolean result = false;
		Short type = Short.valueOf(dataFunctionForm.getType());//获取到添加数据功能的类型
		Integer productId = new Integer(dataFunctionForm.getProductId());
		DataFunctionBusiness dfb = new DataFunctionBusiness();
		RequirementBusiness rb = new RequirementBusiness();
		IfpugProduct product = (IfpugProduct)rb.getProductById(productId);
		
		
		if(type.equals(Short.valueOf("0"))){//如果是ILF，将记录添加到Ifpug_ILF表格中
			IfpugIlf ii = new IfpugIlf();
			//新建一个IfpugIlf实体bean,并赋值
			ii.setFileType(type);
			ii.setIlfName(new String(dataFunctionForm.getName().getBytes("ISO-8859-1"),"GB2312"));
			ii.setIlfDesp(new String(dataFunctionForm.getDesp().getBytes("ISO-8859-1"),"GB2312"));
			ii.setUfpMethod(Short.valueOf(dataFunctionForm.getUfpMethod()));
			ii.setIfpugProduct(product);
			result = dfb.insertIlf(ii);
		}
		else {//如果是EIF，将记录添加Ifpug_Eif表格中
			IfpugEif ie = new IfpugEif();
			//新建一个IfpugEif实体bean,并赋值
			ie.setEifDesp(new String(dataFunctionForm.getName().getBytes("ISO-8859-1"),"GB2312"));
			ie.setEifName(new String(dataFunctionForm.getDesp().getBytes("ISO-8859-1"),"GB2312"));
			ie.setFileType(type);
			ie.setUfpMethod(Short.valueOf(dataFunctionForm.getUfpMethod()));
			ie.setIfpugProduct(product);
			result = dfb.insertEif(ie);
		}
	
		if(result==true){
		   return mapping.findForward("success");
		}else{
		   return mapping.findForward("failure");
		}
	}
}