/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.action;

import java.io.UnsupportedEncodingException;

import hibernate.IFPUG.IfpugEif;
import hibernate.IFPUG.IfpugIlf;
import hibernate.IFPUG.IfpugEifRet;
import hibernate.IFPUG.IfpugIlfRet;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.IFPUG.DataFunctionBusiness;
import struts.IFPUG.form.RetForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-30-2010
 * 
 * XDoclet definition:
 * @struts.action path="/editRet" name="retForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/IFPUG/dataFunction/editRet.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/IFPUG/failure.jsp" contextRelative="true"
 */
public class EditRetAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 * @throws UnsupportedEncodingException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException, UnsupportedEncodingException {
		RetForm retForm = (RetForm) form;// TODO Auto-generated method stub
		
		//获取editRet.jsp页面传过来的retId
		Integer retId = new Integer(retForm.getId());
		//获取editRet.jsp页面传过来的type
		Short type = new Short(retForm.getType());
		DataFunctionBusiness dfb = new DataFunctionBusiness();//业务逻辑层 
		boolean result = false;
		if(type == 0){//如果是ILF类型的RET
			IfpugIlfRet iir = (IfpugIlfRet)dfb.queryIlfRetById(retId); 
			iir.setIlfRetName(new String(retForm.getRetName().getBytes("ISO-8859-1"),"GB2312"));
			iir.setIlfRetDesp(new String(retForm.getRetDesp().getBytes("ISO-8859-1"),"GB2312"));
			result = dfb.updateRet(iir);
		}
		else {//如果是EIF类型的RET
			IfpugEifRet ier = (IfpugEifRet)dfb.queryEifRetById(retId); 
			ier.setEifRetName(new String(retForm.getRetName().getBytes("ISO-8859-1"),"GB2312"));
			ier.setEifRetDesp(new String(retForm.getRetDesp().getBytes("ISO-8859-1"),"GB2312"));
			result = dfb.updateRet(ier);
		}	
		if(result==true){
			   return mapping.findForward("success");
		}else{
			  return mapping.findForward("failure");
		}
	}
}