/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.action;

import java.io.UnsupportedEncodingException;

import hibernate.IFPUG.IfpugEi;
import hibernate.IFPUG.IfpugEo;
import hibernate.IFPUG.IfpugEq;
import hibernate.IFPUG.IfpugFunction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.IFPUG.RequirementBusiness;
import struts.IFPUG.form.ElementaryProcessForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-24-2010
 * 
 * XDoclet definition:
 * @struts.action path="/editElementaryProcess" name="elementaryProcessForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/IFPUG/requirement/elementaryProcessList.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/IFPUG/failure.jsp" contextRelative="true"
 */
public class EditElementaryProcessAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws UnsupportedEncodingException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws UnsupportedEncodingException {
		ElementaryProcessForm elementaryProcessForm = (ElementaryProcessForm) form;// TODO Auto-generated method stub
		//获取elementaryProcessList.jsp页面传过来的epId
		Integer epId = new Integer(elementaryProcessForm.getId());	
		Integer type = Integer.valueOf(elementaryProcessForm.getEpType());
		RequirementBusiness rb = new RequirementBusiness();
		Object epObject = rb.getElementaryProcessById(type,epId);
		
		boolean result = false;
		String ufpMethod = null;
		//更新数据库中EI\EI\EQ表的数据
		switch(type){
			case 0: 
				IfpugEi ei = (IfpugEi)epObject;
				ei.setEiDesp(new String(elementaryProcessForm.getEpDesp().getBytes("ISO-8859-1"),"GB2312"));
				ei.setEiName(new String(elementaryProcessForm.getEpName().getBytes("ISO-8859-1"),"GB2312"));
				ei.setEpType(Short.valueOf(elementaryProcessForm.getEpType()));
				ei.setMeasureStatus(Short.valueOf(elementaryProcessForm.getMeasureStatus()));
				result = rb.updateElementaryProcess(ei);
				break;
			case 1:
				IfpugEo eo = (IfpugEo)epObject;
				eo.setEoDesp(new String(elementaryProcessForm.getEpDesp().getBytes("ISO-8859-1"),"GB2312"));
				eo.setEoName(new String(elementaryProcessForm.getEpName().getBytes("ISO-8859-1"),"GB2312"));
				eo.setEpType(Short.valueOf(elementaryProcessForm.getEpType()));
				eo.setMeasureStatus(Short.valueOf(elementaryProcessForm.getMeasureStatus()));
				result = rb.updateElementaryProcess(eo);
				break;
			case 2:
				IfpugEq eq = (IfpugEq)epObject;
				eq.setEqDesp(new String(elementaryProcessForm.getEpDesp().getBytes("ISO-8859-1"),"GB2312"));
				eq.setEqName(new String(elementaryProcessForm.getEpName().getBytes("ISO-8859-1"),"GB2312"));
				eq.setEpType(Short.valueOf(elementaryProcessForm.getEpType()));
				eq.setMeasureStatus(Short.valueOf(elementaryProcessForm.getMeasureStatus()));
				result = rb.updateElementaryProcess(eq);
				break;
		}
	
		if(result==true){
		   return mapping.findForward("success");
		}else{
		   return mapping.findForward("failure");
		}
	}
}