/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.IFPUG.action;

import java.io.UnsupportedEncodingException;

import hibernate.IFPUG.IfpugEif;
import hibernate.IFPUG.IfpugIlf;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.hibernate.HibernateException;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import business.IFPUG.DataFunctionBusiness;
import business.IFPUG.RequirementBusiness;
import struts.IFPUG.form.DataFunctionForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-29-2010
 * 
 * XDoclet definition:
 * @struts.action path="/editDataFunction" name="dataFunctionForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/IFPUG/dataFunction/dataFunctionList.jsp" contextRelative="true"
 * @struts.action-forward name="failure" path="/IFPUG/failure.jsp" contextRelative="true"
 */
public class EditDataFunctionAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws HibernateException 
	 * @throws UnsupportedEncodingException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws HibernateException, UnsupportedEncodingException {
		DataFunctionForm dataFunctionForm = (DataFunctionForm) form;// TODO Auto-generated method stub
		//获取editDataFunction.jsp页面传过来的dfId
		Integer dfId = new Integer(dataFunctionForm.getId());
		//获取type（是EIF\ILF）
		Integer type = Integer.valueOf(dataFunctionForm.getType());
		DataFunctionBusiness dfb = new DataFunctionBusiness();
		boolean result = false;
		if(type == 0){//如果是ILF类型
			IfpugIlf ilf = (IfpugIlf)dfb.queryIlfById(dfId);
			ilf.setIlfName(new String(dataFunctionForm.getName().getBytes("ISO-8859-1"),"GB2312"));
			ilf.setIlfDesp(new String(dataFunctionForm.getDesp().getBytes("ISO-8859-1"),"GB2312"));
			result = dfb.updateDataFunction(ilf);
		}
		else{
			IfpugEif eif = (IfpugEif)dfb.queryEifById(dfId);
			eif.setEifName(new String(dataFunctionForm.getName().getBytes("ISO-8859-1"),"GB2312"));
			eif.setEifDesp(new String(dataFunctionForm.getDesp().getBytes("ISO-8859-1"),"GB2312"));
			result = dfb.updateDataFunction(eif);
		}		
		if(result==true){
			   return mapping.findForward("success");
		}else{
			  return mapping.findForward("failure");
		}
	}
}